version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.55.0
      - image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Rust Up Stable
          command: "rustup default stable"
      - run:
          name: Cargo Version
          command: "cargo --version"
      - run:
          name: Lint Code - clippy
          command: "cargo clippy"
      - run:
          name: Lint Code - rustfmt
          command: "cargo fmt --all -- --check"
      - run:
          name: Run Tests
          command: "cargo test"
      - save_cache:
          paths:
            - ~/.cargo
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
