version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.54.0
    steps:
      - checkout
      - run:
          name: Rust Up Nightly
          command: "rustup default nightly"
      - run:
          name: Cargo Version
          command: "cargo --version"
      - run:
          name: Lint Code
          command: "cargo clippy"
      - run:
          name: Run Tests
          command: "cargo test"
